### ISSUE TITLE
The empty list is written as NIL, which SMT-LIB does not understand

### ISSUE THREAD

**Issue by edouardklein** [GrammaTech/cl-smt-lib#5]
Hi !

I ran into a small problem. Here is some dummy code that illustrates the issue:

```
(defparameter smt (make-smt "z3" "-in" "-smt2"))
(setf *smt-debug* t)
(write-to-smt smt #!'((set-option :produce-models true)
                      (set-logic QF_LIA)
                      (declare-fun toto () Int)
                      (check-sat)
                      (get-value (toto))))
(read smt)
```

I get:
```
;; WRITE-TO-SMT
(set-option :produce-models true)
(set-logic QF_LIA)
(declare-fun toto NIL Int)
(check-sat)
(get-value (toto))
(ERROR
 "line 3 column 18: Parsing function declaration. Expecting sort list '(' got NIL")
```

which is because the empty list in my `declare-fun` is written as NIL.

My current workaround is to do as suggested on stackoverflow (https://stackoverflow.com/a/40461188):
```
(defmethod print-object :around ((object (eql nil)) stream)
      (write-string "()" stream))
```

But the comments over there say the behavior may be undefined. I don't know enough about Common Lisp to know what the proper fix is, so I have not suggested that in a PR. Right now, this is enough to fix the problem for my use case on SBCL.

Thanks for the library :)

Cheers,

Edouard.

**Comment by eschulte** [comment]
I just pushed up a change which should fix this behavior.  Please let me know and reopen the issue if it doesn't work for you.

Thanks
